# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# batch_project_gss.py
# Created on: 2019-11-13 11:53:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os, sys

inputFolder = arcpy.GetParameterAsText(0)
gss_projection = "PROJCS['Custom',GEOGCS['GCS_Leigon',DATUM['D_Leigon',SPHEROID['Clarke_1880_RGS',6378249.145,293.465]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',899998.392388452],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-1.0],PARAMETER['Scale_Factor',0.99975],PARAMETER['Latitude_Of_Origin',4.666666666666667],UNIT['Foot',0.3048]]"                 
wgs84_projection = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]"

outputFolder = os.path.join(inputFolder, "WGS84")
if not os.path.exists(outputFolder):
    os.makedirs(outputFolder)
    
#Get a list of input shapefiles
inShps = []
for root, dirs, files in os.walk(inputFolder):
    for f in files:
        if f[-4:] == ".shp":
            inShps.append(os.path.join(root, f))
            
for shp in inShps:
    output_shapefile = os.path.join(outputFolder, os.path.basename(shp).replace(".shp", "_WGS84.shp"))
    try:
        # Process: Define Projection
        arcpy.DefineProjection_management(shp, gss_projection)
    except:
        pass
    # Process: Project
    arcpy.Project_management(shp, output_shapefile, wgs84_projection)

